### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by sambattalio** [wtheisen/TerminusBrowse#53]
So it seems like the general consensus on the irc channel (#commandChan on Freenode) is that we might want to change the name of the project now that it is a bit more general and has more features than just 4chan. 

So I guess this thread can be a suggestion thread for name ideas.

Here are a few ideas to get the name juices flowing:

- TermViewer
- commandChannels
- Command
- CommandViewer

@wtheisen thoughts?

**Comment by ginglis13** [comment]
I'll add one (and maybe more if I think of some)

- society

**Comment by ginglis13** [comment]
Some inspiration for brainstorming per a random Medium article:

- What’s the offering?
- Who’s it for?
- What’s the history or context?
- What’s distinctive about this idea?
- What’s the personality of this brand? How should it make people feel?
- What are the overall objectives?
- What are the creative criteria?

**Comment by wtheisen** [comment]
terminusBrowse?

**Comment by wtheisen** [comment]
@ginglis13 unless you say otherwise I think we're going to change to TerminusBrowse

**Comment by ginglis13** [comment]
Nice I like it
