### ISSUE TITLE
Tests Badge Not Displaying Properly

### ISSUE THREAD

**Issue by wtheisen** [wtheisen/TerminusBrowse#64]
Due to the name change the test badge no longer displays properly.

**Comment by ginglis13** [comment]
I believe this can be fixed by changing the link in the README to reference wtheisen/TerminusBrowse instead of wtheisen/commandChan

**Comment by sambattalio** [comment]
I think that's right. If we wanted to verify it is linked exactly how it should be on travis ci site for the repo.
